kind: Service
apiVersion: v1
metadata:
  name: gpsql
  labels:
    app: galaxy
    tier: db
spec:
  clusterIP: None
  ports: 
  - port: 5432
  selector:
    app: galaxy
    tier: db 

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  labels:
    app: galaxy
    tier: db
data:
  POSTGRES_DB: galaxy

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: galaxy
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    # host-specific path for pre-configured Galaxy database files
    path: "/tmp/docker/volumes/postgres"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    app: galaxy
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-deploy
  labels:
    app: galaxy
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galaxy
      tier: db
  template:
    metadata:
      labels:
        app: galaxy
        tier: db
    spec:
      volumes: 
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
      - name: postgres-container
        image: postgres:10.6
        imagePullPolicy: "IfNotPresent"
        envFrom:
        - configMapRef:
            name: postgres-config
        ports: 
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: "/var/lib/postgresql/data"
